/*
 (Game : Rock-paper-scissor) Rock-paper-scissor is a popular game with kids. Write a Java program
that plays the popular scissor-rock-paper game with a user. It should prompt the user to enter 0,1 or 2
with with 0 representing rock, 1 representing paper and 2 representing a scissor. It should then
randomly generate a number between 0 and 2. Based on the number input by the user and the random
number generated by your program, the program should display who has one (the computer or the
user) or whether it is a draw.
(Hint : Use Math.random() to generate a random number between 0 and 2).
 */
package Lap04;
import java.util.Scanner;

public class Lap04 {

    
    public static void main(String[] args) {
         Scanner input=new Scanner(System.in);
            System.out.print("Enter a number(rock=0,paper=1,scissor=2) ");
        int player=input.nextInt();
        int computer=(int)(Math.random()*3);
        
        if(player==computer){
            System.out.print("The computer's choice was rock. It is a draw");
        }
        else if(player==0){
            if(computer==1){
            System.out.println("The computer’s choice was paper. you loose. ");
            }
            else if(computer==2){
                System.out.println("The computer’s choice was scissor. you loose.");
            }
        }
        else if(player==1){
            if(computer==0){
                System.out.print("The computer choice rock,you win.");
            }
            else if(computer==2){
                System.out.print("The computer choice scissors,you loose.");
            }
        }
        else{
            if(computer==0){
                System.out.print("The computer choice rock,you loose.");
                
            }
            else if(computer==1){
                System.out.print("The computer choice paper , you win.");
            }
                
        }
 
    }
    
}
